### ISSUE TITLE
About IUAM V2

### ISSUE THREAD

**Issue by andress134** [unixfox/pupflare#12]
Hello sir, this lib  can be bypass new iuam v2 challenge? like this  (ex url : http://cfuam.audiograb.net/ )

**Comment by unixfox** [comment]
I don't know but anything a chromium can pass then pupflare will be able to pass it.

**Comment by andress134** [comment]
> I don't know but anything a chromium can pass then pupflare will be able to pass it.

What is wrong, i have downlaod your repo, i run npm install and npm start, and get it
I'm using debian 9
```js
root@localhost:~/pupflare# npm start

> pupflare@1.0.0 start /root/pupflare
> node index.js

(node:1561) UnhandledPromiseRejectionWarning: Error: Could not find browser revision 818858. Run "PUPPETEER_PRODUCT=firefox npm install" or "PUPPETEER_PRODUCT=firefox yarn install" to download a supported Firefox browser binary.
    at ChromeLauncher.launch (/root/node_modules/puppeteer-core/lib/cjs/puppeteer/node/Launcher.js:79:23)
    at async PuppeteerExtra.launch (/root/pupflare/node_modules/puppeteer-extra/dist/index.cjs.js:132:25)
    at async /root/pupflare/index.js:27:21
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1561) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1561) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by unixfox** [comment]
Did you execute `npm install`?

**Comment by unixfox** [comment]
I just checked myself and it can't pass the website that you linked: http://cfuam.audiograb.net/

I'll check later what's wrong.

**Comment by andress134** [comment]
> Did you execute `npm install` before `npm start`?

Yes, just download the repo and run 
npm install, she installed chromium
i run now npm start and get this error

**Comment by unixfox** [comment]
I'm sorry but I don't know how to fix your issue. It works fine on my computer and it did worked fine on my other server running Debian 10.

Maybe you could try to install Debian 10 and try again.

**Comment by andress134** [comment]
> I'm sorry but I don't know how to fix your issue. It works fine on my computer and it did worked fine on my other server running Debian 10.
> 
> Maybe you could try to install Debian 10 and try again.

Look working on windows
The problem is next, this lib go to spam my server, use all my cpu and ram, he opened 30  chromium sessions  https://prnt.sc/y0o6ug
Can fix it or set to use just 1 session ?

**Comment by unixfox** [comment]
I haven't claimed that this program is bug free but if something goes wrong while retrieving the page then it's possible that the "tab" stay open and thus create a useless usage of memory and CPU. I opened a new GitHub issue for that: https://github.com/unixfox/pupflare/issues/13

For every new request a new tab get created so no it's not possible to have just one session like you asked. In fact, it's not my fault if there are multiple "chromium" at the same time, that's how chromium behave, I've no control over it, and it's completely normal. That's how every browser do.

**Comment by andress134** [comment]
Ok. thank

**Comment by unixfox** [comment]
I still need to fix this bug related to IUAM v2 so I'll let this issue opened.

**Comment by unixfox** [comment]
I'm able to retrieve the concept of http://cfuam.audiograb.net using pupflare, so I'm going to close this issue.

Not sure when this got fixed but it got probably fixed when upgrading `puppeteer-extra-plugin-stealth` which is a key component in bypassing cloudflare antibot.

**Comment by yokirito** [comment]
Is it possible to run this application on a cpanel hosting that has a node?
