### ISSUE TITLE
error status 415

### ISSUE THREAD

**Issue by skycosth** [unixfox/pupflare#14]
I run it on nodejs on windows it works fine.
But I'm on docker, it shows 415 status, what's the reason?

**Comment by unixfox** [comment]
could you give me the URL that you tried to use?

**Comment by skycosth** [comment]
server docker   203.154.91.31:3000    status":"415"
server windows  122.155.168.151:3000  success




var axios = require('axios');
var data = '{"username":"test","password":"test"}';

var config = {
  method: 'post',
  url: 'http://203.154.91.31:3000?url=https://ambbet-agent.askmebet.cloud/spa/user/login',
  headers: { 
    'sec-ch-ua': '"Chromium";v="88", "Google Chrome";v="88", ";Not A Brand";v="99"', 
    'Accept': 'application/json, text/plain, */*', 
    'sec-ch-ua-mobile': '?0', 
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36', 
    'Content-Type': 'application/json;charset=UTF-8', 
    'Sec-Fetch-Site': 'cross-site', 
    'Sec-Fetch-Mode': 'cors', 
    'Sec-Fetch-Dest': 'empty', 
    'Cookie': '__cfduid=daeae719953ae4b13c6dc4f3bf02959331614026097; __gid=GA1.2.236899844.1614159729; _ga=GA1.2.1109904602.1606902776'
  },
  data : data
};

axios(config)
.then(function (response) {
  console.log(JSON.stringify(response.data));
})
.catch(function (error) {
  console.log(error);
});

**Comment by unixfox** [comment]
Try running the server with the environment variable `PUPPETEER_HEADFUL=1`. I don't know how to do that on Windows so you will have to figure out that by yourself.
This will open the real chromium window page for further diagnose. Then check if something is wrong in the window.

**Comment by skycosth** [comment]
Can I give user: password to multiply so that I can multiply checks?

**Comment by unixfox** [comment]
I don't understand what you mean by that. Please rephrase your sentence.

**Comment by skycosth** [comment]
sftp :  203.154.91.31
user: root
Password : mm@88iBcc

check error 415  pls

**Comment by unixfox** [comment]
I'm sorry, but I'm not logging into an unknown server. I can help you, but I won't solve your issue by directly connecting to your server.

Like I said earlier. Install NodeJS on your Linux server, the required dependencies for puppeteer (https://gist.github.com/tavinus/7effd4b3dac87cb4366e3767679a192f) and then run the two commands described here: https://github.com/unixfox/pupflare#how-to-launch. I'm pretty sure this will solve your issues.

**Comment by skycosth** [comment]
Please advise what operating system to use, now I use centos8.

**Comment by unixfox** [comment]
Debian is a good candidate. The link that I gave you for the required dependencies for puppeteer is for Debian though.

**Comment by skycosth** [comment]
https://gist.github.com/tavinus/7effd4b3dac87cb4366e3767679a192f  
error  
https://prnt.sc/1072fld

**Comment by unixfox** [comment]
I'm closing this issue because your problem is out of scope of this project. This not even an issue related to pupflare.
Just google the error, and you will find plenty of results about it.

Anyway I tested again the Docker image, and it ran fine on my part.
