### ISSUE TITLE
你好 我通过代理 http://localhost:3000/?url=https://www.cambridge.org 使用不了

### ISSUE THREAD

**Issue by meikongli** [unixfox/pupflare#15]
使用你代码启动以后 http://localhost:3000/?url=https://www.cambridge.org  访问此网站访问不了
报错
TypeError: Cannot convert undefined or null to object

**Comment by unixfox** [comment]
Works fine for me.
Please set the environment variable `PUPPETEER_HEADFUL=1` in order to see what's wrong.

**Comment by meikongli** [comment]
你好  还是不行 设置以后打开一直在循环下面的页面   不会跳出循环到首页 一直在重复循环

Checking your browser before accessing cambridge.org.
This process is automatic. Your browser will redirect to your requested content shortly.

Please allow up to 5 seconds…

DDoS protection by Cloudflare
Ray ID: 62a0d4515d5ded0f

**Comment by unixfox** [comment]
Works on my side.
