### ISSUE TITLE
I want to contribute

### ISSUE THREAD

**Issue by svaldnuk** [unixfox/pupflare#19]
Hello good, I want to contribute to the project, do you have any way to contact you with telegram for example?

**Comment by unixfox** [comment]
Hello,

If you want to contribute, I made several issues that explain what kind of enhancement could be done on this project: https://github.com/unixfox/pupflare/issues?q=is%3Aissue+is%3Aopen+label%3Aenhancement. If you have any question about these, feel free to reply on the corresponding issue.

You can also add more features or fixing bugs by creating a new GitHub pull request, we can then discuss it on the created pull request.

If you really need to chat with me, even though if you are contributing to the code we can use comments on GitHub, I'm on matrix with this username: @unixfox:matrix.org.
