### ISSUE TITLE
set PUPPETEER_PROXY, but request got error

### ISSUE THREAD

**Issue by galaxy-wideless-world** [unixfox/pupflare#28]
When i set PUPPETEER_PROXY  ,then start , then request got error as follow:

`
TypeError: Cannot convert undefined or null to object
      at responseHeadersToRemove.forEach.header (/pupflare/index.js:107:78)
`

**Comment by unixfox** [comment]
please post the value of PUPPETEER_PROXY

**Comment by unixfox** [comment]
Closing because the parameter works fine on my end.
