### ISSUE TITLE
Checking if the site connection is secure 

### ISSUE THREAD

**Issue by Fahad-alkamli** [unixfox/pupflare#29]
Greetings,
I am trying to get this to work on Ubuntu but whenever I try the url I get this message back "www.faselhd.club
Checking if the site connection is secure
www.faselhd.club needs to review the security of your connection before proceeding.
Ray ID: 751d3ffc1a4cbc15
Performance & security by [Cloudflare](https://www.cloudflare.com/?utm_source=challenge&utm_campaign=j)
"
it takes a while than redirects to the same page and I will never get the image.
seems like cloudflare doesn't like my ip address.
Is there a fix for this issue?

Url:https://www.faselhd.club/wp-content/uploads/2022/08/272809.jpg

thanks!

**Comment by unixfox** [comment]
Please update pupflare, I just updated the text that wait for the challenge to pass.
