### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by Roboxkin** [unixfox/pupflare#30]
You would at least make a normal instruction, not everyone understands
F:\js>npm i puppeteer
npm ERR! code 1
npm ERR! path F:\js\node_modules\puppeteer
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node install.js
npm ERR! ERROR: Failed to set up Chromium r1045629! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
npm ERR! Error: Download failed: server returned code 403. URL: https://storage.googleapis.com/chromium-browser-snapshots/Win_x64/1045629/chrome-win.zip
npm ERR!     at F:\js\node_modules\puppeteer-core\lib\cjs\puppeteer\node\BrowserFetcher.js:450:27
npm ERR!     at ClientRequest.requestCallback (F:\js\node_modules\puppeteer-core\lib\cjs\puppeteer\node\BrowserFetcher.js:600:13)
npm ERR!     at Object.onceWrapper (node:events:628:26)
npm ERR!     at ClientRequest.emit (node:events:513:28)
npm ERR!     at HTTPParser.parserOnIncomingClient (node:_http_client:693:27)
npm ERR!     at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
npm ERR!     at TLSSocket.socketOnData (node:_http_client:534:22)
npm ERR!     at TLSSocket.emit (node:events:513:28)
npm ERR!     at addChunk (node:internal/streams/readable:324:12)
npm ERR!     at readableAddChunk (node:internal/streams/readable:297:9)

**Comment by unixfox** [comment]
Sorry I don't offer any support.
