### ISSUE TITLE
No license found

### ISSUE THREAD

**Issue by JacksonChen666** [unixfox/pupflare#34]
This project does not seem to have a license declared in an obvious way, or at all. A license should be added (as this project seems to be intended as open source) so that users can run, modify, study, distribute, and use the code.

https://choosealicense.com/no-permission/

**Comment by unixfox** [comment]
Thanks for the notice, I guess that's something I always forgot when open sourcing my work.

Usually when I publish code on GitHub everyone is free to do whatever he wants to do but I have heard that's legally it's not true. No license means it's copyright work.
