### ISSUE TITLE
Help improve pupflare

### ISSUE THREAD

**Issue by andress134** [unixfox/pupflare#5]
Hello, i need help to improve my script to pupflare, if u can help me, here is my script, i tested to improve it but something wrong, get error when try to bypass uam, just get html content and nth

this is my original code

```js
const url= process.argv[2],
  time = process.argv[3],
  req_per_ip = process.argv[4];

let proxies = fs
  .readFileSync(process.argv[5], 'utf-8')
  .replace(/\r/gi, '')
  .split('\n')
  .filter(Boolean);

function send_req() {
  let proxy = proxies[Math.floor(Math.random() * proxies.length)];
  proxy = new HttpsProxyAgent('http://' + proxy);

  return new Promise((resolve, reject) => {
    cloudscraper.get(url, {
      agent: {
        https: proxy,
      },
      cloudflareRetry: 10,
    })
      .catch((error) => {
        console.log(response.body);
        resolve(response);
      })
      .catch((error) => {
        let obj_v = proxies.indexOf(proxy);
        proxies.splice(obj_v, 1);
        console.log(error.message);
        return reject(error.message);
      });
  });
}

setInterval(() => {
    send_req();
})
```

**Comment by unixfox** [comment]
You can stop using cloudscraper at all (**really!**). You just need to use a normal request library like request, got or axios (it's up to you).

I can see that you are trying to rotate a list of proxies (`HttpsProxyAgent`), this won't really work because the requests go through pupflare and not your program. Implementing this feature into pupflare is something that I can do if you really want to.

I tried to adapt your code with the request library but it seems like you didn't post all your code so this may not directly work:
```js
const url= process.argv[2],
time = process.argv[3],

function send_req() {
  return new Promise((resolve, reject) => {
    request.get("http://localhost:3000/?url=" + url)
      .catch((error) => {
        console.log(response.body);
        resolve(response);
      })
      .catch((error) => {
        console.log(error.message);
        return reject(error.message);
      });
  });
}

setInterval(() => {
    send_req();
})
```

**Comment by andress134** [comment]
> You can stop using cloudscraper at all (**really!**) because the point is that pupflare automatically do the job to solve the "cloudflare challenge". You just need to use a normal request library like request, got or axios (it's up to you).
> 
> I can see that you are trying to rotate a list of proxies (`HttpsProxyAgent`), this won't really work because the external requests go through pupflare and not your program. Implementing this feature into pupflare is something that I can do if you really want to.
> 
> I tried to adapt your code with the request library but it seems like you didn't post all your code so this may not directly work:
> 
> ```js
> const url= process.argv[2],
> time = process.argv[3],
> 
> function send_req() {
>   return new Promise((resolve, reject) => {
>     request.get("http://localhost:3000/?url=" + url)
>       .catch((error) => {
>         console.log(response.body);
>         resolve(response);
>       })
>       .catch((error) => {
>         console.log(error.message);
>         return reject(error.message);
>       });
>   });
> }
> 
> setInterval(() => {
>     send_req();
> })
> ```

> koa-puppeteer@1.0.0 start /var/tmp/uam/pupflare
> node index.js

(node:3925) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
/var/tmp/uam/pupflare/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome: error while loading shared libraries: libXcursor.so.1: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/var/tmp/uam/pupflare/node_modules/puppeteer/lib/launcher/BrowserRunner.js:159:20)
    at Interface.<anonymous> (/var/tmp/uam/pupflare/node_modules/puppeteer/lib/launcher/BrowserRunner.js:149:65)
    at Interface.emit (events.js:327:22)
    at Interface.close (readline.js:424:8)
    at Socket.onend (readline.js:202:10)
    at Socket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1224:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3925) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3925) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by unixfox** [comment]
@andress134 if my reply solve your problem then feel free to close this issue.

**Comment by andress134** [comment]
> @andress134 if my reply solve your problem then feel free to close this issue.

(node:17257) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 294)
(node:17257) UnhandledPromiseRejectionWarning: TypeError: request.get(...).catch is not a function

**Comment by unixfox** [comment]
I don't use request that often, so I forgot that request doesn't have promises.
You'll need to replace catch with `.on('error'` like this:
```js
const url= process.argv[2],
time = process.argv[3],

function send_req() {
  return new Promise((resolve, reject) => {
    request.get("http://localhost:3000/?url=" + url)
      .on('error', function(err) {
    	console.error(err)
  	  })
  });
}

setInterval(() => {
    send_req();
})
```

If you still have any error with the request library then please consult the documentation: https://github.com/request/request#table-of-contents because I'm not going to continue to help you if it's not an error directly related to my program and that can be quickly resolved by "Googling" it :smiley:.
You may also switch to a better alternative to request: https://github.com/sindresorhus/got because request got deprecated on Feb 11th 2020.
