### ISSUE TITLE
CAPTCHA

### ISSUE THREAD

**Issue by OfficialGDog** [unixfox/pupflare#6]
Please enable cookies.
One more step
Please complete the security check to access xxxx
Why do I have to complete a CAPTCHA?
Completing the CAPTCHA proves you are a human and gives you temporary access to the web property.

What can I do to prevent this in the future?
If you are on a personal connection, like at home, you can run an anti-virus scan on your device to make sure it is not infected with malware.

If you are at an office or shared network, you can ask the network administrator to run a scan across the network looking for misconfigured or infected devices.

Another way to prevent getting this page in the future is to use Privacy Pass. You may need to download version 2.0 now from the Chrome Web Store.

Cloudflare Ray ID: 59d8864a485673ad • Your IP: -------- • Performance & security by Cloudflare

**Comment by unixfox** [comment]
Cloudflare probably flagged your IP and I can't do anything about that unfortunately.
You may share your code though so that I can try to replicate your problem.
