### ISSUE TITLE
get JSON response?

### ISSUE THREAD

**Issue by christopherjbaker** [unixfox/pupflare#7]
Is there a way I can get a raw JSON response as a result? Right now, pages that return JSON are being wrapped in chome's json browser, so its got a bunch of html around it.

Edit: I'm having this issue with all non-html types. I have a temporary workaround for JSON, but other types are just giving `Bad Request: The browser (or proxy) sent a request that this server could not understand.`

**Comment by unixfox** [comment]
This should be fixed with the latest commit: https://github.com/unixfox/pupflare/commit/1e6136e05ae923f25922f034a0c70074f45875c0
Let me know if that's the case.

**Comment by christopherjbaker** [comment]
Yep that fixed it. Thanks!
